### ISSUE TITLE
Make email footer changable

### ISSUE THREAD

**Issue by Takuto88** [Takuto88/owncloud-app-invite#3]
Edit signature/footer of email so users can change it with their own as suggested in [this comment](https://github.com/owncloud/core/issues/788#issuecomment-24208867) by zefrenchemen.

**Comment by Takuto88** [comment]
Purely for documentation: This cannot be changed by apps themselves. However, the footer can be changed using ownCloud's theming support.
1. Create a new folder called `mytheme` in [owncloud-root]/themes/  
2. Create a new file called `defaults.php` in [owncloud-root]/themes/mytheme
3. Put in these contents: 

``` php
<?php
class OC_Theme {
  private $name;
  private $slogan;

  function __construct() {
    $this->name = "My Company";
    $this->slogan = "My Company's slogan";
  }


  public function getName() {
    return $this->name;
  }

  public function getSlogan(){
    return $this->slogan;
  }
}
```
1. Save the file, and activate the theme in config.php by adding the following option to the config array

``` php
$CONFIG = array (
  // ... 
  'theme' => 'mytheme',
 // ....
);
```

Note: This also has impact in other places like the personal or administration pane.

**Comment by zefrenchemen** [comment]
Actually, to add to the previous solution, the $LongFooter function should be added as well. Although it seems to serve the same purpose as the $slogan, one affects the email footer, the other the login page footer. Not sure of other implications, but if these two serve the same purpose they are not completely redundant.

<?php
class OC_Theme {
private $name;
private $slogan;

function __construct() {
$this->name = "My Company";
$this->slogan = "My Company's slogan.";
}
   public function getLongFooter() {
        return '<a href="#">Link</a> <br>Some long text.';
    }

public function getName() {
return $this->name;
}

public function getSlogan(){
return $this->slogan;
}
}
